name: GamiStreamSnag
options:
  minimumXcodeGenVersion: 2.0.0
  deploymentTarget:
    macOS: "15.0"
settings:
  base:
    PRODUCT_NAME: GamiStreamSnag
    CURRENT_PROJECT_VERSION: 1.0
    PRODUCT_BUNDLE_IDENTIFIER: com.gamistreamsnag.app
    INFOPLIST_FILE: App/Resources/Info.plist
targets:
  GamiStreamSnag:
    type: application
    platform: macOS
    sources:
      - path: App/Sources
      - path: App/Models
        name: Models 
        type: group
    resources:
      - path: App/Resources
    settings:
      base:
        SWIFT_VERSION: 6.2
    scheme:
      testTargets: []


